


version: '3'
services:

  # Ce service doit dépendre de redis et mysql
  zerofiltretech-blog:
    image: imzerofiltre/zerofiltretech-blog:177_stable
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - /vault:/vault/secrets/config


  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379


  mysql:
    image: mysql:8.0.30
    restart: always
    ports:
      - "3306:3306"

    # Définir les valeur de mysql mot de passe et mot de passe route sur ${SPRING_DATASOURCE_PASSWORD}, user= ${SPRING_DATASOURCE_USERNAME}, nom de la base de données=${SPRING_DATASOURCE_DATABASE}  On peut utiliser un fichier .env pour définir les variables d'environnement(SPRING_DATASOURCE_PASSWORD, SPRING_DATASOURCE_DATABASE, SPRING_DATASOURCE_USERNAME)
    # Vous pouvez vous servir de la documentation officielle de mysql pour plus d'informations https://hub.docker.com/_/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
