version: '3'
services:
  app:
    build: .
    image: zerofiltre-blog-backend
    container_name: zerofiltre-blog-backend
    ports:
      - 80:80
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./observability/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-storage:/loki/data
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./observability/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./observability/tmp:/tmp
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./observability/geolite2-city.mmdb:/etc/promtail/geolite2-city.mmdb:ro
    command: "-config.file=/etc/promtail/promtail-config.yaml"
    restart: always
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/alert.rules:/etc/prometheus/rules/alert.rules:ro
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - monitoring


volumes:
  grafana-storage:
  loki-storage:

