#System env variables takes precedence over application-x.yml(properties) variables !!!
# Ex: if ${SERVER_PORT} is 7000 in your system env var, defining 8000 in this file will have no effect !!! Spring will always pick 7000 to use as server.port
management:
    endpoints:
        web:
            exposure:
                include: '*'

    endpoint:
        health:
            show-details: always
logging:
  level:
    org:
      zalando.logbook : TRACE
      hibernate.SQL: INFO
    tech.zerofiltre: DEBUG
server:
  port: 80

logbook:
  write.max-body-size: 50
  exclude:
  - '**swagger-ui**'
  - '**v3/api-docs**'
  - '**/swagger-resources/**'
  - '**/webjars/**'
  - '**/actuator/**'
  - '**/csrf'

bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    url: .*
    metrics:
        enabled: true
        tags:
          - key: IP
            expression: getRemote()
            types: REJECTED_COUNTER
    http-response-body: "{\"apiVersion\": \"1.0\",\"error\": {\"status\": \"429\",\"message\": \"TOO MANY REQUESTS!\"}}"
    rate-limits:
    - expression: "getRemote()"
      bandwidths:
      - capacity: 5
        time: 10
        unit: seconds




spring:
  cache:
    cache-names:
    - rate-limit-buckets

  liquibase:
    change-log: classpath:/liquibase/db/changelog/db.changelog-dev.yaml
  mvc:
    log-request-details: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: philippesimo@zerofiltre.tech
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    username: blog_api_dev
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://blog-api-db.cttqyqreuonm.eu-west-3.rds.amazonaws.com:3306/blogapidb_dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update




  messages:
    fallback-to-system-locale: false
    basename: i18n.messages

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  env: dev
  infra:
    security:
      jwt:
        expiration-seconds: 86400
        secret: JwtSecretKey
        prefix: Bearer
        header: Authorization
        uri: /auth/**
    api:
      github:
        root-url: https://api.github.com/
        client-id:
        client-secret:
      stackoverflow:
        version: 2.3
        root-url: https://api.stackexchange.com/
        key:
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "*"
    reminder-rate: 864000000 #10 days
    reminder-initial-delay: 864000000 #10 days
    max-attempts: 2


