scrape_configs:
  - job_name: 'telegraf'
    scrape_interval: 5s
    static_configs:
      - targets: ['telegraf:9273']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']