apiVersion: v1
kind: ConfigMap
metadata:
  name: zerofiltre-blog-api-ngassam-william
  namespace: zerofiltre-bootcamp
data:
  logging_level_org_springframework: DEBUG
  logging_level_org_hibernate_sql: DEBUG
  logging_level_tech_zerofiltre: DEBUG

  server_port: "80"

  throttling_capacity: "5"
  throttling_time_seconds: "10"

  spring_liquibase_changelog: classpath:/liquibase/db/changelog/db.changelog-dev.yaml

  spring_mail_host: smtp.gmail.com
  spring_mail_port: "587"
  spring_mail_username: ngaswilly77@gmail.com
  spring_datasource_username: sql7593951
  spring_datasource_url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7593951
  hibernate_ddl_auto: update
  zerofiltre_env: dev

  security_jwt_expiration: "60" #seconds
  security_verification_token_expiration: "604800" #7 days
  security_jwt_uri: /auth/**


  allowed_origins_pattern: '*'

  reminder_rate: "864000000" #10 days
  reminder_initial_delay: "864000000" #10 days