apiVersion: v1
kind: Secret
metadata:
  name: zerofiltre-blog-api-ngassam-william
  namespace: zerofiltre-bootcamp 
data:
  security_jwt_secret: Snd0U2VjcmV0S2V5
  spring_datasource_password: QmhqRTlLSk1aYg==
  spring_mail_password: QmhqRTlLSk1aYg==
type: Opaque