

name: Java CI/CD with Maven and k8s

on:
  push:
    branches: 
      - 'otlp*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      tag_number : ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build and run unit tests with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Integration tests
      run: mvn failsafe:integration-test
 
    - name: Cache OpenTelemetry Java agent
      id: cache-otel-agent
      uses: actions/cache@v4
      with:
        path: opentelemetry-javaagent.jar
        key: ${{ runner.os }}-otel-agent-v2.5.0
        restore-keys: |
          ${{ runner.os }}-otel-agent-
          

    - name: Download OpenTelemetry Java agent
      if: steps.cache-otel-agent.outputs.cache-hit != 'true'
      run: wget -O opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.5.0/opentelemetry-javaagent.jar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/zerofiltretech-blog:${{ github.run_number }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
